<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed'); 
$config['protocol'] = 'smtp';
$config['smtp_host'] = 'ssl://smtp.googlemail.com';
$config['smtp_port'] = 465;
$config['smtp_user'] = 'jvargasa91@gmail.com';
$config['smtp_pass'] = '206810945';
$config['smtp_timeout'] = '7';
$config['charset']    = 'utf-8';
$config['newline']    = "\r\n";
$config['mailtype'] = 'html';
$config['validation'] = TRUE; 